theme: jekyll-theme-minimal
title: "Jacob Dichter"
description: Portfolio site
markdown: kramdown
collections:
  posts:
    output: true
    tags: false
github_username: jacobdichter
linkedin_username: jacobdichter
